### ISSUE TITLE
callback url

### ISSUE THREAD

**Issue by zakaria-ahmed** [chrisandrewca/shopify-nextjs#1]
Hi, I was trying out your starter code
can you tell me which endpoint you handle the code hmac etc. and convert it into access token ?
I tried api/validate-token but didnt work

**Comment by chrisandrewca** [comment]
Hi @zakaria-ahmed , thanks for checking out my project. The hmac is checked in [isValidShopifyRequest](https://github.com/chrisandrewca/shopify-nextjs/blob/356c7c384c48fc5530073e26e6a510972b6b3041/server/shopify-server.js#L72).

The full flow starts at [/api/install-granted.js](https://github.com/chrisandrewca/shopify-nextjs/blob/master/pages/api/shopify/install-granted.js)
1. Whitelist /api/install-granted.js in the Shopify app admin dashboard
2. Navigate to [/app/login](https://github.com/chrisandrewca/shopify-nextjs/blob/master/pages/app/login.js) which calls [redirectToShopifyAuth](https://github.com/chrisandrewca/shopify-nextjs/blob/356c7c384c48fc5530073e26e6a510972b6b3041/pages/app/login.js#L8) to begin the install process
3. Once install is clicked in Shopify; you'll be redirected to the whitelisted /api/install-granted
4. [addShopifyUser](https://github.com/chrisandrewca/shopify-nextjs/blob/356c7c384c48fc5530073e26e6a510972b6b3041/server/shopify-server.js#L8) will be called to request the access_token from Shopify and save the users details. During this process the hmac will be tested to ensure it's a valid request.

Thanks again for checking this out.

**Comment by zakaria-ahmed** [comment]
I get this error here GET https://31f78827.ngrok.io/api/install-granted?code=xxxxxxhmac=xxxxxx&shop=xxxxx&timestamp=1580845572 404 (Not Found)
im using ngrok

Also do you know what should be specified in the cookie domain FOR_SERVER_CODE_COOKIE_DOMAIN that is the only one I have not filled out

**Comment by chrisandrewca** [comment]
Hmm.. I'm not sure. Is your URL white listed? If so, are you able to ping that API with Postman or CURL?

That constant is used [here](https://github.com/chrisandrewca/shopify-nextjs/blob/5f2095575b7079d5b682a1b82e2eeb976fbce7bb/pages/api/shopify/install-granted.js#L17). Probably just your ngrok url. It associates the cookie with the sites domain.

**Comment by zakaria-ahmed** [comment]
I actually got it working, when I moved it out of the shopify folder, very weird
but thanks it works now.

**Comment by chrisandrewca** [comment]
Ok good. It sounds like your whitelisted url didn’t include the Shopify uri though.

**Comment by zakaria-ahmed** [comment]
you mean the shopName.myshopify.com ?

**Comment by zakaria-ahmed** [comment]
I generally have had some troubles making it work, it would be nice to know how far you came
for example once it logged in, it became an embedded app and redirected back to /app/login

**Comment by chrisandrewca** [comment]
I’m curious, what’s your whitelisted url for the app in the Shopify partner dashboard?

**Comment by zakaria-ahmed** [comment]
not sure if is cause of the tunnelling, shouldnt be 
on app url: https://strange-treefrog-24.localtunnel.me/
Whitelisted redirection URL´s 
https://strange-treefrog-24.localtunnel.me/api/install-granted

**Comment by chrisandrewca** [comment]
Yeah the url is wrong which is why you needed to move the install granted api. It should be https://strange-treefrog-24.localtunnel.me/api/shopify/install-granted. The readme is ambiguous in this regard. Sorry about that!

**Comment by zakaria-ahmed** [comment]
No problem, thanks it seem to be working fine, how do you go about deploying since I dont wanna use tunnelling, I saw you set it up as serverless ?
is that the easiest approach ? 
I tried to build as a server and got this error Error occurred prerendering page "/app/shopify-welcome": TypeError: ctx.res.writeHead is not a function

**Comment by chrisandrewca** [comment]
I'm not targeting serverless anymore in my builds but next still produces lambdas? It sounds like [getInitialProps ](https://github.com/chrisandrewca/shopify-nextjs/blob/356c7c384c48fc5530073e26e6a510972b6b3041/components/with/app-auth.js#L22)ran on the client where the ctx object isn't available. That would be a bug.

Part of it is somehow the welcome page was loaded while the client was unauthorized. Possibly a page refresh or a link? The other part is implementing a redirect when the ctx is unavailable. Do you have steps to repro?

**Comment by zakaria-ahmed** [comment]
yes so i wanted to produce an export. by adding     "export": "next export"  in package.json scripts and running npm run export
