### ISSUE TITLE
Oauth error invalid_request: The Shopify API application does not support oauth

### ISSUE THREAD

**Issue by impactcolor** [chrisandrewca/shopify-nextjs#2]
Thanks for sharing this code!
I'm trying to set it up using the details on the home page.

BASE_URL=
SHOPIFY_REDIRECT_URL=https://mystore.shopify.com
FOR_SERVER_CODE_COOKIE_DOMAIN=
FOR_SERVER_CODE_SHOPIFY_API_KEY=99999apikey
FOR_SERVER_CODE_SHOPIFY_API_SECRET=9999secret key
FOR_SERVER_CODE_JWT_SECRET=

The base_url, cookie domino, and jwt secret I left blank, not sure what to put there.

I install and run dev.  It takes me to the install page.
Shopify NextJS page and I click Login
I then login to my store and I get the error:
`Oauth error invalid_request: The Shopify API application does not support oauth`

The api details I got from trying two different ways.
1. I made a private app and used those credentials.
2. I did a public app and got those credentials.

Any idea what I'm doing wrong?

**Comment by chrisandrewca** [comment]
Hey @impactcolor thanks for trying out my project. Base url is the base domain like www.yoursite.com, same for cookie domain. The redirect url should be yoursite.com/api/shopify/install-granted, and should also be added to the whitelist urls in the Shopify app partner dashboard. The api key and secret come from the partner dashboard as well. The jwt secret can be anything you want, but the more random the better. Let me know how it goes!

**Comment by impactcolor** [comment]
Thank you.  I tried that and got an internal error.
```
{
  "error": "Internal error."
}
```
On the redirect after it went through the process.
Here is the response:
`api/shopify/install-granted?code=b2d890e4a75edca82881b465b862279a&hmac=db4b422d629264114345f9423ac07d1c6b0d34e23f610d4f2fd66b95f1a5a30b&shop=itsyoo.myshopify.com&timestamp=1581705343`

Here is .env (part of it)
```
BASE_URL=https://2ed32b69.ngrok.io
SHOPIFY_REDIRECT_URL=https://2ed32b69.ngrok.io/api/shopify/install-granted
FOR_SERVER_CODE_COOKIE_DOMAIN=http://itsyoo.myshopify.com/
```

**Comment by impactcolor** [comment]
Specifically when getting this:
`GET /api/shopify/install-granted    `

**Comment by chrisandrewca** [comment]
Once again can you confirm in App Setup on the partner dashboard:
App URL is https://your-domain.com/app
Whitelisted redirection URL(s) is https://your-domain.com/api/shopify/install-granted

At the top of install-granted.js put an:
```
await log('install-granted', { query: req.query });
```
and paste the log here.

The FOR_SERVER_CODE_COOKIE_DOMAIN must be the domain your serving the cookie from. So it should be the same as the domain in BASE_URL.

**Comment by impactcolor** [comment]
I got further ahead! But now I have a 404:
https://330ebf1d.ngrok.io/api/shopify/install-granted?code=311917b5dfa1dbffae5cf5994d00beb7&hmac=fb0e672336188b5c186a1f62bf2bfc216491f1bc4e830e54cfc093e55453c8bc&shop=itsyoo.myshopify.com&timestamp=1582245823 

I couldn't find where to get that log.

```
BASE_URL= https://330ebf1d.ngrok.io
SHOPIFY_REDIRECT_URL= https://330ebf1d.ngrok.io/api/shopify/install-granted
FOR_SERVER_CODE_COOKIE_DOMAIN=https://330ebf1d.ngrok.io
FOR_SERVER_CODE_SHOPIFY_API_KEY=blahblah
FOR_SERVER_CODE_SHOPIFY_API_SECRET=blahblah
FOR_SERVER_CODE_JWT_SECRET=eyJhbGciOiJIUzI1Nasdfasdf5cCI6IkpXVCJ9
```

In the app setup on partner dashboard:
App URL:
`https://330ebf1d.ngrok.io/app`

Whitelisted redirection URL(s)
`https://330ebf1d.ngrok.io/api/shopify/install-granted`
Any ideas?  THANKS FOR ALL YOUR HELP THUS FAR!!!! YOU'RE AWESOME

**Comment by chrisandrewca** [comment]
Hey @impactcolor, put `await log('install-granted', { query: req.query });` [here](https://github.com/chrisandrewca/shopify-nextjs/blob/356c7c384c48fc5530073e26e6a510972b6b3041/pages/api/shopify/install-granted.js#L8).

I see your BASE_URL and REDIRECT_URL start with spaces. That might the the issue.

**Comment by impactcolor** [comment]
@chrisandrewca Thanks for your help on this.  I received an internal error again after those changes and tracked it down to here.
db.js
`await db.put(query.shop, user);`
 I changed it to:
`await db.put(query.shop, user, err => console.log(err))`
I get a 404.  I noticed the URL contains two // between database and my shop name.
```
config:
   { url: 'https://app.easydb.io/database//itsyoo.myshopify.com',
     method: 'post',
     data:
```

**Comment by impactcolor** [comment]
Well dumb me.  I hadn't created a db at easyDB.io!
